-- Generated by scripts/plan-accounts-migration.mjs from @royer/auth 0.1.0-rc.4 (central mode).
-- Accounts: local principals, sessions and the issuer link. No passwords live here.

create table if not exists "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table if not exists "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table if not exists "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table if not exists "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table if not exists "federationTransaction" ("id" text not null primary key, "state" text not null unique, "binding" text not null, "verifier" text not null, "nonce" text not null, "returnPath" text not null, "expiresAt" timestamptz not null);

create table if not exists "federationIdentity" ("id" text not null primary key, "issuer" text not null, "subject" text not null, "userId" text not null references "user" ("id") on delete cascade);

create table if not exists "federationGrant" ("id" text not null primary key, "sessionId" text not null unique references "session" ("id") on delete cascade, "issuer" text not null, "subject" text not null, "sid" text not null, "accessToken" text not null, "expiresAt" timestamptz not null);

create table if not exists "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);

create index if not exists "session_userId_idx" on "session" ("userId");

create index if not exists "account_userId_idx" on "account" ("userId");

create index if not exists "verification_identifier_idx" on "verification" ("identifier");

create index if not exists "federationTransaction_expiresAt_idx" on "federationTransaction" ("expiresAt");

create index if not exists "federationGrant_expiresAt_idx" on "federationGrant" ("expiresAt");

create unique index if not exists "federationIdentity_issuer_subject_uidx" on "federationIdentity" ("issuer", "subject");

create index if not exists "federationGrant_issuer_sid_idx" on "federationGrant" ("issuer", "sid");
