-- Generated by scripts/plan-accounts-upgrade.mjs from @royer/auth 0.1.0-rc.5 (central mode),
-- on top of the earlier files in migrations/. Additive only.

alter table "federationTransaction" add column if not exists "completedSessionId" text;

alter table "federationTransaction" add column if not exists "claims" integer default 0;
